# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scraper_pb2 as scraper__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScrapeHome = channel.unary_unary(
                '/scraper.ScraperService/ScrapeHome',
                request_serializer=scraper__pb2.Empty.SerializeToString,
                response_deserializer=scraper__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.ScrapeList = channel.unary_unary(
                '/scraper.ScraperService/ScrapeList',
                request_serializer=scraper__pb2.ListRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScrapeHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrapeList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScrapeHome': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeHome,
                    request_deserializer=scraper__pb2.Empty.FromString,
                    response_serializer=scraper__pb2.HomeResponse.SerializeToString,
            ),
            'ScrapeList': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeList,
                    request_deserializer=scraper__pb2.ListRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraper.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScrapeHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/ScrapeHome',
            scraper__pb2.Empty.SerializeToString,
            scraper__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrapeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/ScrapeList',
            scraper__pb2.ListRequest.SerializeToString,
            scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
