# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scraper_pb2 as scraper__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/scraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScrapeHome = channel.unary_unary(
                '/scraper.ScraperService/ScrapeHome',
                request_serializer=scraper__pb2.Empty.SerializeToString,
                response_deserializer=scraper__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.ScrapeList = channel.unary_unary(
                '/scraper.ScraperService/ScrapeList',
                request_serializer=scraper__pb2.ListRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMoviesByGenre = channel.unary_unary(
                '/scraper.ScraperService/GetMoviesByGenre',
                request_serializer=scraper__pb2.GenreRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.SearchMovies = channel.unary_unary(
                '/scraper.ScraperService/SearchMovies',
                request_serializer=scraper__pb2.SearchRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMoviesByFeature = channel.unary_unary(
                '/scraper.ScraperService/GetMoviesByFeature',
                request_serializer=scraper__pb2.FeatureRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMoviesByCountry = channel.unary_unary(
                '/scraper.ScraperService/GetMoviesByCountry',
                request_serializer=scraper__pb2.CountryRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMoviesByYear = channel.unary_unary(
                '/scraper.ScraperService/GetMoviesByYear',
                request_serializer=scraper__pb2.YearRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSpecialPage = channel.unary_unary(
                '/scraper.ScraperService/GetSpecialPage',
                request_serializer=scraper__pb2.SpecialPageRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMovieDetail = channel.unary_unary(
                '/scraper.ScraperService/GetMovieDetail',
                request_serializer=scraper__pb2.MovieDetailRequest.SerializeToString,
                response_deserializer=scraper__pb2.MovieDetailResponse.FromString,
                _registered_method=True)
        self.GetSeriesHome = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesHome',
                request_serializer=scraper__pb2.Empty.SerializeToString,
                response_deserializer=scraper__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.GetSeriesByGenre = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesByGenre',
                request_serializer=scraper__pb2.GenreRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.SearchSeries = channel.unary_unary(
                '/scraper.ScraperService/SearchSeries',
                request_serializer=scraper__pb2.SearchRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSeriesByFeature = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesByFeature',
                request_serializer=scraper__pb2.FeatureRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSeriesByCountry = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesByCountry',
                request_serializer=scraper__pb2.CountryRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSeriesByYear = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesByYear',
                request_serializer=scraper__pb2.YearRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSeriesSpecialPage = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesSpecialPage',
                request_serializer=scraper__pb2.SpecialPageRequest.SerializeToString,
                response_deserializer=scraper__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSeriesDetail = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesDetail',
                request_serializer=scraper__pb2.MovieDetailRequest.SerializeToString,
                response_deserializer=scraper__pb2.SeriesDetailResponse.FromString,
                _registered_method=True)
        self.GetSeriesEpisode = channel.unary_unary(
                '/scraper.ScraperService/GetSeriesEpisode',
                request_serializer=scraper__pb2.SeriesEpisodeRequest.SerializeToString,
                response_deserializer=scraper__pb2.SeriesEpisodeResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScrapeHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrapeList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByGenre(self, request, context):
        """New RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByFeature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpecialPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMovieDetail(self, request, context):
        """Detail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesHome(self, request, context):
        """Series RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesByGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesByFeature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesByCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesByYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesSpecialPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesDetail(self, request, context):
        """Series Detail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScrapeHome': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeHome,
                    request_deserializer=scraper__pb2.Empty.FromString,
                    response_serializer=scraper__pb2.HomeResponse.SerializeToString,
            ),
            'ScrapeList': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeList,
                    request_deserializer=scraper__pb2.ListRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetMoviesByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByGenre,
                    request_deserializer=scraper__pb2.GenreRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'SearchMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMovies,
                    request_deserializer=scraper__pb2.SearchRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetMoviesByFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByFeature,
                    request_deserializer=scraper__pb2.FeatureRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetMoviesByCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByCountry,
                    request_deserializer=scraper__pb2.CountryRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetMoviesByYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByYear,
                    request_deserializer=scraper__pb2.YearRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSpecialPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpecialPage,
                    request_deserializer=scraper__pb2.SpecialPageRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetMovieDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovieDetail,
                    request_deserializer=scraper__pb2.MovieDetailRequest.FromString,
                    response_serializer=scraper__pb2.MovieDetailResponse.SerializeToString,
            ),
            'GetSeriesHome': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesHome,
                    request_deserializer=scraper__pb2.Empty.FromString,
                    response_serializer=scraper__pb2.HomeResponse.SerializeToString,
            ),
            'GetSeriesByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesByGenre,
                    request_deserializer=scraper__pb2.GenreRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'SearchSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSeries,
                    request_deserializer=scraper__pb2.SearchRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSeriesByFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesByFeature,
                    request_deserializer=scraper__pb2.FeatureRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSeriesByCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesByCountry,
                    request_deserializer=scraper__pb2.CountryRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSeriesByYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesByYear,
                    request_deserializer=scraper__pb2.YearRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSeriesSpecialPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesSpecialPage,
                    request_deserializer=scraper__pb2.SpecialPageRequest.FromString,
                    response_serializer=scraper__pb2.ListResponse.SerializeToString,
            ),
            'GetSeriesDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesDetail,
                    request_deserializer=scraper__pb2.MovieDetailRequest.FromString,
                    response_serializer=scraper__pb2.SeriesDetailResponse.SerializeToString,
            ),
            'GetSeriesEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesEpisode,
                    request_deserializer=scraper__pb2.SeriesEpisodeRequest.FromString,
                    response_serializer=scraper__pb2.SeriesEpisodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraper.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScrapeHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/ScrapeHome',
            scraper__pb2.Empty.SerializeToString,
            scraper__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrapeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/ScrapeList',
            scraper__pb2.ListRequest.SerializeToString,
            scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMoviesByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetMoviesByGenre',
            proto_dot_scraper__pb2.GenreRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/SearchMovies',
            proto_dot_scraper__pb2.SearchRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMoviesByFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetMoviesByFeature',
            proto_dot_scraper__pb2.FeatureRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMoviesByCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetMoviesByCountry',
            proto_dot_scraper__pb2.CountryRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMoviesByYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetMoviesByYear',
            proto_dot_scraper__pb2.YearRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpecialPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSpecialPage',
            proto_dot_scraper__pb2.SpecialPageRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMovieDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetMovieDetail',
            proto_dot_scraper__pb2.MovieDetailRequest.SerializeToString,
            proto_dot_scraper__pb2.MovieDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesHome',
            proto_dot_scraper__pb2.Empty.SerializeToString,
            proto_dot_scraper__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesByGenre',
            proto_dot_scraper__pb2.GenreRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/SearchSeries',
            proto_dot_scraper__pb2.SearchRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesByFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesByFeature',
            proto_dot_scraper__pb2.FeatureRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesByCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesByCountry',
            proto_dot_scraper__pb2.CountryRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesByYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesByYear',
            proto_dot_scraper__pb2.YearRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesSpecialPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesSpecialPage',
            proto_dot_scraper__pb2.SpecialPageRequest.SerializeToString,
            proto_dot_scraper__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesDetail',
            proto_dot_scraper__pb2.MovieDetailRequest.SerializeToString,
            proto_dot_scraper__pb2.SeriesDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/GetSeriesEpisode',
            proto_dot_scraper__pb2.SeriesEpisodeRequest.SerializeToString,
            proto_dot_scraper__pb2.SeriesEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
