// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenreRequest) Reset() {
	*x = GenreRequest{}
	mi := &file_proto_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreRequest) ProtoMessage() {}

func (x *GenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreRequest.ProtoReflect.Descriptor instead.
func (*GenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GenreRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GenreRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureType   string                 `protobuf:"bytes,1,opt,name=feature_type,json=featureType,proto3" json:"feature_type,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureRequest) Reset() {
	*x = FeatureRequest{}
	mi := &file_proto_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRequest) ProtoMessage() {}

func (x *FeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRequest.ProtoReflect.Descriptor instead.
func (*FeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureRequest) GetFeatureType() string {
	if x != nil {
		return x.FeatureType
	}
	return ""
}

func (x *FeatureRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type CountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountrySlug   string                 `protobuf:"bytes,1,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryRequest) Reset() {
	*x = CountryRequest{}
	mi := &file_proto_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryRequest) ProtoMessage() {}

func (x *CountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryRequest.ProtoReflect.Descriptor instead.
func (*CountryRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *CountryRequest) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

func (x *CountryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type YearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearRequest) Reset() {
	*x = YearRequest{}
	mi := &file_proto_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearRequest) ProtoMessage() {}

func (x *YearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearRequest.ProtoReflect.Descriptor instead.
func (*YearRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *YearRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SpecialPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageName      string                 `protobuf:"bytes,1,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialPageRequest) Reset() {
	*x = SpecialPageRequest{}
	mi := &file_proto_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialPageRequest) ProtoMessage() {}

func (x *SpecialPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialPageRequest.ProtoReflect.Descriptor instead.
func (*SpecialPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *SpecialPageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *SpecialPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type MovieDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieDetailRequest) Reset() {
	*x = MovieDetailRequest{}
	mi := &file_proto_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieDetailRequest) ProtoMessage() {}

func (x *MovieDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieDetailRequest.ProtoReflect.Descriptor instead.
func (*MovieDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *MovieDetailRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Movie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle   *string                `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3,oneof" json:"original_title,omitempty"`
	Thumbnail       *string                `protobuf:"bytes,4,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	Synopsis        *string                `protobuf:"bytes,5,opt,name=synopsis,proto3,oneof" json:"synopsis,omitempty"`
	Rating          *float32               `protobuf:"fixed32,6,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Duration        *int64                 `protobuf:"varint,7,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Year            *int32                 `protobuf:"varint,8,opt,name=year,proto3,oneof" json:"year,omitempty"`
	DatePublished   *string                `protobuf:"bytes,9,opt,name=date_published,json=datePublished,proto3,oneof" json:"date_published,omitempty"`
	LabelQuality    *string                `protobuf:"bytes,10,opt,name=label_quality,json=labelQuality,proto3,oneof" json:"label_quality,omitempty"`
	Genre           *string                `protobuf:"bytes,11,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	OriginalPageUrl *string                `protobuf:"bytes,12,opt,name=original_page_url,json=originalPageUrl,proto3,oneof" json:"original_page_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetOriginalTitle() string {
	if x != nil && x.OriginalTitle != nil {
		return *x.OriginalTitle
	}
	return ""
}

func (x *Movie) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *Movie) GetSynopsis() string {
	if x != nil && x.Synopsis != nil {
		return *x.Synopsis
	}
	return ""
}

func (x *Movie) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Movie) GetDuration() int64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Movie) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Movie) GetDatePublished() string {
	if x != nil && x.DatePublished != nil {
		return *x.DatePublished
	}
	return ""
}

func (x *Movie) GetLabelQuality() string {
	if x != nil && x.LabelQuality != nil {
		return *x.LabelQuality
	}
	return ""
}

func (x *Movie) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *Movie) GetOriginalPageUrl() string {
	if x != nil && x.OriginalPageUrl != nil {
		return *x.OriginalPageUrl
	}
	return ""
}

type HomeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []*Movie               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	ViewAllUrl    *string                `protobuf:"bytes,3,opt,name=view_all_url,json=viewAllUrl,proto3,oneof" json:"view_all_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeSection) Reset() {
	*x = HomeSection{}
	mi := &file_proto_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeSection) ProtoMessage() {}

func (x *HomeSection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeSection.ProtoReflect.Descriptor instead.
func (*HomeSection) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *HomeSection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HomeSection) GetValue() []*Movie {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HomeSection) GetViewAllUrl() string {
	if x != nil && x.ViewAllUrl != nil {
		return *x.ViewAllUrl
	}
	return ""
}

type HomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*HomeSection         `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeResponse) Reset() {
	*x = HomeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeResponse) ProtoMessage() {}

func (x *HomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeResponse.ProtoReflect.Descriptor instead.
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *HomeResponse) GetSections() []*HomeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPage     int32                  `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,4,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	NextPageUrl   *string                `protobuf:"bytes,5,opt,name=next_page_url,json=nextPageUrl,proto3,oneof" json:"next_page_url,omitempty"`
	PrevPageUrl   *string                `protobuf:"bytes,6,opt,name=prev_page_url,json=prevPageUrl,proto3,oneof" json:"prev_page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pagination) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

func (x *Pagination) GetNextPageUrl() string {
	if x != nil && x.NextPageUrl != nil {
		return *x.NextPageUrl
	}
	return ""
}

func (x *Pagination) GetPrevPageUrl() string {
	if x != nil && x.PrevPageUrl != nil {
		return *x.PrevPageUrl
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *ListResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PlayerUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUrl) Reset() {
	*x = PlayerUrl{}
	mi := &file_proto_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUrl) ProtoMessage() {}

func (x *PlayerUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUrl.ProtoReflect.Descriptor instead.
func (*PlayerUrl) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PlayerUrl) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MoviePerson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageUrl       string                 `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoviePerson) Reset() {
	*x = MoviePerson{}
	mi := &file_proto_scraper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoviePerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviePerson) ProtoMessage() {}

func (x *MoviePerson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviePerson.ProtoReflect.Descriptor instead.
func (*MoviePerson) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{15}
}

func (x *MoviePerson) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoviePerson) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

type CountryMovie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageUrl       string                 `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryMovie) Reset() {
	*x = CountryMovie{}
	mi := &file_proto_scraper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryMovie) ProtoMessage() {}

func (x *CountryMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryMovie.ProtoReflect.Descriptor instead.
func (*CountryMovie) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{16}
}

func (x *CountryMovie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CountryMovie) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageUrl       string                 `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_scraper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{17}
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

type MovieDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	Votes         int64                  `protobuf:"varint,2,opt,name=votes,proto3" json:"votes,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,3,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PlayerUrls    []*PlayerUrl           `protobuf:"bytes,5,rep,name=player_urls,json=playerUrls,proto3" json:"player_urls,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,6,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	Directors     []*MoviePerson         `protobuf:"bytes,7,rep,name=directors,proto3" json:"directors,omitempty"`
	MovieStars    []*MoviePerson         `protobuf:"bytes,8,rep,name=movie_stars,json=movieStars,proto3" json:"movie_stars,omitempty"`
	Countries     []*CountryMovie        `protobuf:"bytes,9,rep,name=countries,proto3" json:"countries,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,10,rep,name=genres,proto3" json:"genres,omitempty"`
	SimilarMovies []*Movie               `protobuf:"bytes,11,rep,name=similar_movies,json=similarMovies,proto3" json:"similar_movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieDetail) Reset() {
	*x = MovieDetail{}
	mi := &file_proto_scraper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieDetail) ProtoMessage() {}

func (x *MovieDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieDetail.ProtoReflect.Descriptor instead.
func (*MovieDetail) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{18}
}

func (x *MovieDetail) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *MovieDetail) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *MovieDetail) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *MovieDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MovieDetail) GetPlayerUrls() []*PlayerUrl {
	if x != nil {
		return x.PlayerUrls
	}
	return nil
}

func (x *MovieDetail) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *MovieDetail) GetDirectors() []*MoviePerson {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *MovieDetail) GetMovieStars() []*MoviePerson {
	if x != nil {
		return x.MovieStars
	}
	return nil
}

func (x *MovieDetail) GetCountries() []*CountryMovie {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *MovieDetail) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieDetail) GetSimilarMovies() []*Movie {
	if x != nil {
		return x.SimilarMovies
	}
	return nil
}

type MovieDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *MovieDetail           `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieDetailResponse) Reset() {
	*x = MovieDetailResponse{}
	mi := &file_proto_scraper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieDetailResponse) ProtoMessage() {}

func (x *MovieDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieDetailResponse.ProtoReflect.Descriptor instead.
func (*MovieDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{19}
}

func (x *MovieDetailResponse) GetDetail() *MovieDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SeriesEpisodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesEpisodeRequest) Reset() {
	*x = SeriesEpisodeRequest{}
	mi := &file_proto_scraper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesEpisodeRequest) ProtoMessage() {}

func (x *SeriesEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesEpisodeRequest.ProtoReflect.Descriptor instead.
func (*SeriesEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{20}
}

func (x *SeriesEpisodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SeriesEpisodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeNumber int32                  `protobuf:"varint,1,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	PlayerUrls    []*PlayerUrl           `protobuf:"bytes,2,rep,name=player_urls,json=playerUrls,proto3" json:"player_urls,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,3,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	DownloadUrl   *string                `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3,oneof" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesEpisodeResponse) Reset() {
	*x = SeriesEpisodeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesEpisodeResponse) ProtoMessage() {}

func (x *SeriesEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesEpisodeResponse.ProtoReflect.Descriptor instead.
func (*SeriesEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{21}
}

func (x *SeriesEpisodeResponse) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *SeriesEpisodeResponse) GetPlayerUrls() []*PlayerUrl {
	if x != nil {
		return x.PlayerUrls
	}
	return nil
}

func (x *SeriesEpisodeResponse) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *SeriesEpisodeResponse) GetDownloadUrl() string {
	if x != nil && x.DownloadUrl != nil {
		return *x.DownloadUrl
	}
	return ""
}

type EpisodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeNumber int32                  `protobuf:"varint,1,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	EpisodeUrl    string                 `protobuf:"bytes,2,opt,name=episode_url,json=episodeUrl,proto3" json:"episode_url,omitempty"`
	PlayerUrls    []*PlayerUrl           `protobuf:"bytes,3,rep,name=player_urls,json=playerUrls,proto3" json:"player_urls,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,4,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeList) Reset() {
	*x = EpisodeList{}
	mi := &file_proto_scraper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeList) ProtoMessage() {}

func (x *EpisodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeList.ProtoReflect.Descriptor instead.
func (*EpisodeList) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{22}
}

func (x *EpisodeList) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *EpisodeList) GetEpisodeUrl() string {
	if x != nil {
		return x.EpisodeUrl
	}
	return ""
}

func (x *EpisodeList) GetPlayerUrls() []*PlayerUrl {
	if x != nil {
		return x.PlayerUrls
	}
	return nil
}

func (x *EpisodeList) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

type SeasonList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentSeason int32                  `protobuf:"varint,1,opt,name=current_season,json=currentSeason,proto3" json:"current_season,omitempty"`
	TotalSeason   int32                  `protobuf:"varint,2,opt,name=total_season,json=totalSeason,proto3" json:"total_season,omitempty"`
	EpisodeList   []*EpisodeList         `protobuf:"bytes,3,rep,name=episode_list,json=episodeList,proto3" json:"episode_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonList) Reset() {
	*x = SeasonList{}
	mi := &file_proto_scraper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonList) ProtoMessage() {}

func (x *SeasonList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonList.ProtoReflect.Descriptor instead.
func (*SeasonList) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{23}
}

func (x *SeasonList) GetCurrentSeason() int32 {
	if x != nil {
		return x.CurrentSeason
	}
	return 0
}

func (x *SeasonList) GetTotalSeason() int32 {
	if x != nil {
		return x.TotalSeason
	}
	return 0
}

func (x *SeasonList) GetEpisodeList() []*EpisodeList {
	if x != nil {
		return x.EpisodeList
	}
	return nil
}

type SeriesDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieDetail   *MovieDetail           `protobuf:"bytes,1,opt,name=movie_detail,json=movieDetail,proto3" json:"movie_detail,omitempty"`
	SeasonName    string                 `protobuf:"bytes,2,opt,name=season_name,json=seasonName,proto3" json:"season_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SeasonList    []*SeasonList          `protobuf:"bytes,4,rep,name=season_list,json=seasonList,proto3" json:"season_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesDetail) Reset() {
	*x = SeriesDetail{}
	mi := &file_proto_scraper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesDetail) ProtoMessage() {}

func (x *SeriesDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesDetail.ProtoReflect.Descriptor instead.
func (*SeriesDetail) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{24}
}

func (x *SeriesDetail) GetMovieDetail() *MovieDetail {
	if x != nil {
		return x.MovieDetail
	}
	return nil
}

func (x *SeriesDetail) GetSeasonName() string {
	if x != nil {
		return x.SeasonName
	}
	return ""
}

func (x *SeriesDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeriesDetail) GetSeasonList() []*SeasonList {
	if x != nil {
		return x.SeasonList
	}
	return nil
}

type SeriesDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *SeriesDetail          `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesDetailResponse) Reset() {
	*x = SeriesDetailResponse{}
	mi := &file_proto_scraper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesDetailResponse) ProtoMessage() {}

func (x *SeriesDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesDetailResponse.ProtoReflect.Descriptor instead.
func (*SeriesDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{25}
}

func (x *SeriesDetailResponse) GetDetail() *SeriesDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type AnimeGenre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeGenre) Reset() {
	*x = AnimeGenre{}
	mi := &file_proto_scraper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeGenre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeGenre) ProtoMessage() {}

func (x *AnimeGenre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeGenre.ProtoReflect.Descriptor instead.
func (*AnimeGenre) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{26}
}

func (x *AnimeGenre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnimeGenre) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Anime struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleJapanese   string                 `protobuf:"bytes,2,opt,name=title_japanese,json=titleJapanese,proto3" json:"title_japanese,omitempty"`
	OriginalPageUrl string                 `protobuf:"bytes,3,opt,name=original_page_url,json=originalPageUrl,proto3" json:"original_page_url,omitempty"`
	Thumbnail       string                 `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Score           string                 `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"`
	Producer        string                 `protobuf:"bytes,6,opt,name=producer,proto3" json:"producer,omitempty"`
	Type            string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TotalEpisodes   string                 `protobuf:"bytes,9,opt,name=total_episodes,json=totalEpisodes,proto3" json:"total_episodes,omitempty"`
	Duration        string                 `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	ReleaseDate     string                 `protobuf:"bytes,11,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	ReleasedDay     string                 `protobuf:"bytes,12,opt,name=released_day,json=releasedDay,proto3" json:"released_day,omitempty"`
	Studio          string                 `protobuf:"bytes,13,opt,name=studio,proto3" json:"studio,omitempty"`
	Genre           []*AnimeGenre          `protobuf:"bytes,14,rep,name=genre,proto3" json:"genre,omitempty"`
	Rating          string                 `protobuf:"bytes,15,opt,name=rating,proto3" json:"rating,omitempty"`
	Episodes        []*AnimeEpisode        `protobuf:"bytes,16,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Anime) Reset() {
	*x = Anime{}
	mi := &file_proto_scraper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anime) ProtoMessage() {}

func (x *Anime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anime.ProtoReflect.Descriptor instead.
func (*Anime) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{27}
}

func (x *Anime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Anime) GetTitleJapanese() string {
	if x != nil {
		return x.TitleJapanese
	}
	return ""
}

func (x *Anime) GetOriginalPageUrl() string {
	if x != nil {
		return x.OriginalPageUrl
	}
	return ""
}

func (x *Anime) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Anime) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *Anime) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Anime) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Anime) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Anime) GetTotalEpisodes() string {
	if x != nil {
		return x.TotalEpisodes
	}
	return ""
}

func (x *Anime) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Anime) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Anime) GetReleasedDay() string {
	if x != nil {
		return x.ReleasedDay
	}
	return ""
}

func (x *Anime) GetStudio() string {
	if x != nil {
		return x.Studio
	}
	return ""
}

func (x *Anime) GetGenre() []*AnimeGenre {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *Anime) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Anime) GetEpisodes() []*AnimeEpisode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type AnimeEpisode struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Title              string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	PlayerUrl          string                 `protobuf:"bytes,2,opt,name=player_url,json=playerUrl,proto3" json:"player_url,omitempty"`
	PageUrl            string                 `protobuf:"bytes,3,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	PostedBy           string                 `protobuf:"bytes,4,opt,name=posted_by,json=postedBy,proto3" json:"posted_by,omitempty"`
	PreviousEpisodeUrl string                 `protobuf:"bytes,5,opt,name=previous_episode_url,json=previousEpisodeUrl,proto3" json:"previous_episode_url,omitempty"`
	NextEpisodeUrl     string                 `protobuf:"bytes,6,opt,name=next_episode_url,json=nextEpisodeUrl,proto3" json:"next_episode_url,omitempty"`
	SeeAllEpisodesUrl  string                 `protobuf:"bytes,7,opt,name=see_all_episodes_url,json=seeAllEpisodesUrl,proto3" json:"see_all_episodes_url,omitempty"`
	ReleaseDate        string                 `protobuf:"bytes,8,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	ReleaseTime        string                 `protobuf:"bytes,9,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	EpisodeNumber      string                 `protobuf:"bytes,10,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	ListEpisode        []*AnimeEpisodeItem    `protobuf:"bytes,11,rep,name=list_episode,json=listEpisode,proto3" json:"list_episode,omitempty"`
	DownloadLinks      []*AnimeDownloadLink   `protobuf:"bytes,12,rep,name=download_links,json=downloadLinks,proto3" json:"download_links,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnimeEpisode) Reset() {
	*x = AnimeEpisode{}
	mi := &file_proto_scraper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeEpisode) ProtoMessage() {}

func (x *AnimeEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeEpisode.ProtoReflect.Descriptor instead.
func (*AnimeEpisode) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{28}
}

func (x *AnimeEpisode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnimeEpisode) GetPlayerUrl() string {
	if x != nil {
		return x.PlayerUrl
	}
	return ""
}

func (x *AnimeEpisode) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *AnimeEpisode) GetPostedBy() string {
	if x != nil {
		return x.PostedBy
	}
	return ""
}

func (x *AnimeEpisode) GetPreviousEpisodeUrl() string {
	if x != nil {
		return x.PreviousEpisodeUrl
	}
	return ""
}

func (x *AnimeEpisode) GetNextEpisodeUrl() string {
	if x != nil {
		return x.NextEpisodeUrl
	}
	return ""
}

func (x *AnimeEpisode) GetSeeAllEpisodesUrl() string {
	if x != nil {
		return x.SeeAllEpisodesUrl
	}
	return ""
}

func (x *AnimeEpisode) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *AnimeEpisode) GetReleaseTime() string {
	if x != nil {
		return x.ReleaseTime
	}
	return ""
}

func (x *AnimeEpisode) GetEpisodeNumber() string {
	if x != nil {
		return x.EpisodeNumber
	}
	return ""
}

func (x *AnimeEpisode) GetListEpisode() []*AnimeEpisodeItem {
	if x != nil {
		return x.ListEpisode
	}
	return nil
}

func (x *AnimeEpisode) GetDownloadLinks() []*AnimeDownloadLink {
	if x != nil {
		return x.DownloadLinks
	}
	return nil
}

type AnimeEpisodeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageUrl       string                 `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeEpisodeItem) Reset() {
	*x = AnimeEpisodeItem{}
	mi := &file_proto_scraper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeEpisodeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeEpisodeItem) ProtoMessage() {}

func (x *AnimeEpisodeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeEpisodeItem.ProtoReflect.Descriptor instead.
func (*AnimeEpisodeItem) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{29}
}

func (x *AnimeEpisodeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnimeEpisodeItem) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

type AnimeDownloadLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Quality       string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeDownloadLink) Reset() {
	*x = AnimeDownloadLink{}
	mi := &file_proto_scraper_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeDownloadLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeDownloadLink) ProtoMessage() {}

func (x *AnimeDownloadLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeDownloadLink.ProtoReflect.Descriptor instead.
func (*AnimeDownloadLink) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{30}
}

func (x *AnimeDownloadLink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnimeDownloadLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AnimeDownloadLink) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *AnimeDownloadLink) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *AnimeDownloadLink) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type PaginationAnime struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalPages      int32                  `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage     int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	HasNext         bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious     bool                   `protobuf:"varint,4,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	NextPageUrl     string                 `protobuf:"bytes,5,opt,name=next_page_url,json=nextPageUrl,proto3" json:"next_page_url,omitempty"`
	PreviousPageUrl string                 `protobuf:"bytes,6,opt,name=previous_page_url,json=previousPageUrl,proto3" json:"previous_page_url,omitempty"`
	PageNumbers     []int32                `protobuf:"varint,7,rep,packed,name=page_numbers,json=pageNumbers,proto3" json:"page_numbers,omitempty"`
	PerPage         int32                  `protobuf:"varint,8,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaginationAnime) Reset() {
	*x = PaginationAnime{}
	mi := &file_proto_scraper_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationAnime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationAnime) ProtoMessage() {}

func (x *PaginationAnime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationAnime.ProtoReflect.Descriptor instead.
func (*PaginationAnime) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{31}
}

func (x *PaginationAnime) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationAnime) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationAnime) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationAnime) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *PaginationAnime) GetNextPageUrl() string {
	if x != nil {
		return x.NextPageUrl
	}
	return ""
}

func (x *PaginationAnime) GetPreviousPageUrl() string {
	if x != nil {
		return x.PreviousPageUrl
	}
	return ""
}

func (x *PaginationAnime) GetPageNumbers() []int32 {
	if x != nil {
		return x.PageNumbers
	}
	return nil
}

func (x *PaginationAnime) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type AnimeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animes        []*Anime               `protobuf:"bytes,1,rep,name=animes,proto3" json:"animes,omitempty"`
	Pagination    *PaginationAnime       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeListResponse) Reset() {
	*x = AnimeListResponse{}
	mi := &file_proto_scraper_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeListResponse) ProtoMessage() {}

func (x *AnimeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeListResponse.ProtoReflect.Descriptor instead.
func (*AnimeListResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{32}
}

func (x *AnimeListResponse) GetAnimes() []*Anime {
	if x != nil {
		return x.Animes
	}
	return nil
}

func (x *AnimeListResponse) GetPagination() *PaginationAnime {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *AnimeListResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AnimeGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*AnimeGenre          `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeGenresResponse) Reset() {
	*x = AnimeGenresResponse{}
	mi := &file_proto_scraper_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeGenresResponse) ProtoMessage() {}

func (x *AnimeGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeGenresResponse.ProtoReflect.Descriptor instead.
func (*AnimeGenresResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{33}
}

func (x *AnimeGenresResponse) GetGenres() []*AnimeGenre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type AnimePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimePageRequest) Reset() {
	*x = AnimePageRequest{}
	mi := &file_proto_scraper_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimePageRequest) ProtoMessage() {}

func (x *AnimePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimePageRequest.ProtoReflect.Descriptor instead.
func (*AnimePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{34}
}

func (x *AnimePageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type AnimeSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeSearchRequest) Reset() {
	*x = AnimeSearchRequest{}
	mi := &file_proto_scraper_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeSearchRequest) ProtoMessage() {}

func (x *AnimeSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeSearchRequest.ProtoReflect.Descriptor instead.
func (*AnimeSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{35}
}

func (x *AnimeSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AnimeSearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type AnimeUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeUrlRequest) Reset() {
	*x = AnimeUrlRequest{}
	mi := &file_proto_scraper_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeUrlRequest) ProtoMessage() {}

func (x *AnimeUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeUrlRequest.ProtoReflect.Descriptor instead.
func (*AnimeUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{36}
}

func (x *AnimeUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AnimeDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anime         *Anime                 `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeDetailResponse) Reset() {
	*x = AnimeDetailResponse{}
	mi := &file_proto_scraper_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeDetailResponse) ProtoMessage() {}

func (x *AnimeDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeDetailResponse.ProtoReflect.Descriptor instead.
func (*AnimeDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{37}
}

func (x *AnimeDetailResponse) GetAnime() *Anime {
	if x != nil {
		return x.Anime
	}
	return nil
}

type AnimeEpisodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       *AnimeEpisode          `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeEpisodeResponse) Reset() {
	*x = AnimeEpisodeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeEpisodeResponse) ProtoMessage() {}

func (x *AnimeEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeEpisodeResponse.ProtoReflect.Descriptor instead.
func (*AnimeEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{38}
}

func (x *AnimeEpisodeResponse) GetEpisode() *AnimeEpisode {
	if x != nil {
		return x.Episode
	}
	return nil
}

var File_proto_scraper_proto protoreflect.FileDescriptor

const file_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scraper.proto\x12\ascraper\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\vListRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"6\n" +
	"\fGenreRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"9\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"G\n" +
	"\x0eFeatureRequest\x12!\n" +
	"\ffeature_type\x18\x01 \x01(\tR\vfeatureType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"G\n" +
	"\x0eCountryRequest\x12!\n" +
	"\fcountry_slug\x18\x01 \x01(\tR\vcountrySlug\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"5\n" +
	"\vYearRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"E\n" +
	"\x12SpecialPageRequest\x12\x1b\n" +
	"\tpage_name\x18\x01 \x01(\tR\bpageName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"(\n" +
	"\x12MovieDetailRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xaa\x04\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tH\x00R\roriginalTitle\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\x04 \x01(\tH\x01R\tthumbnail\x88\x01\x01\x12\x1f\n" +
	"\bsynopsis\x18\x05 \x01(\tH\x02R\bsynopsis\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x06 \x01(\x02H\x03R\x06rating\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\a \x01(\x03H\x04R\bduration\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\b \x01(\x05H\x05R\x04year\x88\x01\x01\x12*\n" +
	"\x0edate_published\x18\t \x01(\tH\x06R\rdatePublished\x88\x01\x01\x12(\n" +
	"\rlabel_quality\x18\n" +
	" \x01(\tH\aR\flabelQuality\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\v \x01(\tH\bR\x05genre\x88\x01\x01\x12/\n" +
	"\x11original_page_url\x18\f \x01(\tH\tR\x0foriginalPageUrl\x88\x01\x01B\x11\n" +
	"\x0f_original_titleB\f\n" +
	"\n" +
	"_thumbnailB\v\n" +
	"\t_synopsisB\t\n" +
	"\a_ratingB\v\n" +
	"\t_durationB\a\n" +
	"\x05_yearB\x11\n" +
	"\x0f_date_publishedB\x10\n" +
	"\x0e_label_qualityB\b\n" +
	"\x06_genreB\x14\n" +
	"\x12_original_page_url\"}\n" +
	"\vHomeSection\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x03(\v2\x0e.scraper.MovieR\x05value\x12%\n" +
	"\fview_all_url\x18\x03 \x01(\tH\x00R\n" +
	"viewAllUrl\x88\x01\x01B\x0f\n" +
	"\r_view_all_url\"@\n" +
	"\fHomeResponse\x120\n" +
	"\bsections\x18\x01 \x03(\v2\x14.scraper.HomeSectionR\bsections\"\xfa\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1d\n" +
	"\n" +
	"total_page\x18\x02 \x01(\x05R\ttotalPage\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x04 \x01(\bR\ahasPrev\x12'\n" +
	"\rnext_page_url\x18\x05 \x01(\tH\x00R\vnextPageUrl\x88\x01\x01\x12'\n" +
	"\rprev_page_url\x18\x06 \x01(\tH\x01R\vprevPageUrl\x88\x01\x01B\x10\n" +
	"\x0e_next_page_urlB\x10\n" +
	"\x0e_prev_page_url\"k\n" +
	"\fListResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.scraper.MovieR\x06movies\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.scraper.PaginationR\n" +
	"pagination\"1\n" +
	"\tPlayerUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"<\n" +
	"\vMoviePerson\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpage_url\x18\x02 \x01(\tR\apageUrl\"=\n" +
	"\fCountryMovie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpage_url\x18\x02 \x01(\tR\apageUrl\"6\n" +
	"\x05Genre\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpage_url\x18\x02 \x01(\tR\apageUrl\"\xe0\x03\n" +
	"\vMovieDetail\x12$\n" +
	"\x05movie\x18\x01 \x01(\v2\x0e.scraper.MovieR\x05movie\x12\x14\n" +
	"\x05votes\x18\x02 \x01(\x03R\x05votes\x12!\n" +
	"\frelease_date\x18\x03 \x01(\tR\vreleaseDate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x123\n" +
	"\vplayer_urls\x18\x05 \x03(\v2\x12.scraper.PlayerUrlR\n" +
	"playerUrls\x12\x1f\n" +
	"\vtrailer_url\x18\x06 \x01(\tR\n" +
	"trailerUrl\x122\n" +
	"\tdirectors\x18\a \x03(\v2\x14.scraper.MoviePersonR\tdirectors\x125\n" +
	"\vmovie_stars\x18\b \x03(\v2\x14.scraper.MoviePersonR\n" +
	"movieStars\x123\n" +
	"\tcountries\x18\t \x03(\v2\x15.scraper.CountryMovieR\tcountries\x12&\n" +
	"\x06genres\x18\n" +
	" \x03(\v2\x0e.scraper.GenreR\x06genres\x125\n" +
	"\x0esimilar_movies\x18\v \x03(\v2\x0e.scraper.MovieR\rsimilarMovies\"C\n" +
	"\x13MovieDetailResponse\x12,\n" +
	"\x06detail\x18\x01 \x01(\v2\x14.scraper.MovieDetailR\x06detail\"(\n" +
	"\x14SeriesEpisodeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xcd\x01\n" +
	"\x15SeriesEpisodeResponse\x12%\n" +
	"\x0eepisode_number\x18\x01 \x01(\x05R\repisodeNumber\x123\n" +
	"\vplayer_urls\x18\x02 \x03(\v2\x12.scraper.PlayerUrlR\n" +
	"playerUrls\x12\x1f\n" +
	"\vtrailer_url\x18\x03 \x01(\tR\n" +
	"trailerUrl\x12&\n" +
	"\fdownload_url\x18\x04 \x01(\tH\x00R\vdownloadUrl\x88\x01\x01B\x0f\n" +
	"\r_download_url\"\xab\x01\n" +
	"\vEpisodeList\x12%\n" +
	"\x0eepisode_number\x18\x01 \x01(\x05R\repisodeNumber\x12\x1f\n" +
	"\vepisode_url\x18\x02 \x01(\tR\n" +
	"episodeUrl\x123\n" +
	"\vplayer_urls\x18\x03 \x03(\v2\x12.scraper.PlayerUrlR\n" +
	"playerUrls\x12\x1f\n" +
	"\vtrailer_url\x18\x04 \x01(\tR\n" +
	"trailerUrl\"\x8f\x01\n" +
	"\n" +
	"SeasonList\x12%\n" +
	"\x0ecurrent_season\x18\x01 \x01(\x05R\rcurrentSeason\x12!\n" +
	"\ftotal_season\x18\x02 \x01(\x05R\vtotalSeason\x127\n" +
	"\fepisode_list\x18\x03 \x03(\v2\x14.scraper.EpisodeListR\vepisodeList\"\xb6\x01\n" +
	"\fSeriesDetail\x127\n" +
	"\fmovie_detail\x18\x01 \x01(\v2\x14.scraper.MovieDetailR\vmovieDetail\x12\x1f\n" +
	"\vseason_name\x18\x02 \x01(\tR\n" +
	"seasonName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x124\n" +
	"\vseason_list\x18\x04 \x03(\v2\x13.scraper.SeasonListR\n" +
	"seasonList\"E\n" +
	"\x14SeriesDetailResponse\x12-\n" +
	"\x06detail\x18\x01 \x01(\v2\x15.scraper.SeriesDetailR\x06detail\"2\n" +
	"\n" +
	"AnimeGenre\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x83\x04\n" +
	"\x05Anime\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\x0etitle_japanese\x18\x02 \x01(\tR\rtitleJapanese\x12*\n" +
	"\x11original_page_url\x18\x03 \x01(\tR\x0foriginalPageUrl\x12\x1c\n" +
	"\tthumbnail\x18\x04 \x01(\tR\tthumbnail\x12\x14\n" +
	"\x05score\x18\x05 \x01(\tR\x05score\x12\x1a\n" +
	"\bproducer\x18\x06 \x01(\tR\bproducer\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0etotal_episodes\x18\t \x01(\tR\rtotalEpisodes\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\tR\bduration\x12!\n" +
	"\frelease_date\x18\v \x01(\tR\vreleaseDate\x12!\n" +
	"\freleased_day\x18\f \x01(\tR\vreleasedDay\x12\x16\n" +
	"\x06studio\x18\r \x01(\tR\x06studio\x12)\n" +
	"\x05genre\x18\x0e \x03(\v2\x13.scraper.AnimeGenreR\x05genre\x12\x16\n" +
	"\x06rating\x18\x0f \x01(\tR\x06rating\x121\n" +
	"\bepisodes\x18\x10 \x03(\v2\x15.scraper.AnimeEpisodeR\bepisodes\"\xf6\x03\n" +
	"\fAnimeEpisode\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"player_url\x18\x02 \x01(\tR\tplayerUrl\x12\x19\n" +
	"\bpage_url\x18\x03 \x01(\tR\apageUrl\x12\x1b\n" +
	"\tposted_by\x18\x04 \x01(\tR\bpostedBy\x120\n" +
	"\x14previous_episode_url\x18\x05 \x01(\tR\x12previousEpisodeUrl\x12(\n" +
	"\x10next_episode_url\x18\x06 \x01(\tR\x0enextEpisodeUrl\x12/\n" +
	"\x14see_all_episodes_url\x18\a \x01(\tR\x11seeAllEpisodesUrl\x12!\n" +
	"\frelease_date\x18\b \x01(\tR\vreleaseDate\x12!\n" +
	"\frelease_time\x18\t \x01(\tR\vreleaseTime\x12%\n" +
	"\x0eepisode_number\x18\n" +
	" \x01(\tR\repisodeNumber\x12<\n" +
	"\flist_episode\x18\v \x03(\v2\x19.scraper.AnimeEpisodeItemR\vlistEpisode\x12A\n" +
	"\x0edownload_links\x18\f \x03(\v2\x1a.scraper.AnimeDownloadLinkR\rdownloadLinks\"A\n" +
	"\x10AnimeEpisodeItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpage_url\x18\x02 \x01(\tR\apageUrl\"\x7f\n" +
	"\x11AnimeDownloadLink\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"\xa1\x02\n" +
	"\x0fPaginationAnime\x12\x1f\n" +
	"\vtotal_pages\x18\x01 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x04 \x01(\bR\vhasPrevious\x12\"\n" +
	"\rnext_page_url\x18\x05 \x01(\tR\vnextPageUrl\x12*\n" +
	"\x11previous_page_url\x18\x06 \x01(\tR\x0fpreviousPageUrl\x12!\n" +
	"\fpage_numbers\x18\a \x03(\x05R\vpageNumbers\x12\x19\n" +
	"\bper_page\x18\b \x01(\x05R\aperPage\"\x8b\x01\n" +
	"\x11AnimeListResponse\x12&\n" +
	"\x06animes\x18\x01 \x03(\v2\x0e.scraper.AnimeR\x06animes\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.scraper.PaginationAnimeR\n" +
	"pagination\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"B\n" +
	"\x13AnimeGenresResponse\x12+\n" +
	"\x06genres\x18\x01 \x03(\v2\x13.scraper.AnimeGenreR\x06genres\"&\n" +
	"\x10AnimePageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\">\n" +
	"\x12AnimeSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"#\n" +
	"\x0fAnimeUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\";\n" +
	"\x13AnimeDetailResponse\x12$\n" +
	"\x05anime\x18\x01 \x01(\v2\x0e.scraper.AnimeR\x05anime\"G\n" +
	"\x14AnimeEpisodeResponse\x12/\n" +
	"\aepisode\x18\x01 \x01(\v2\x15.scraper.AnimeEpisodeR\aepisode2\x84\r\n" +
	"\x0eScraperService\x123\n" +
	"\n" +
	"ScrapeHome\x12\x0e.scraper.Empty\x1a\x15.scraper.HomeResponse\x129\n" +
	"\n" +
	"ScrapeList\x12\x14.scraper.ListRequest\x1a\x15.scraper.ListResponse\x12@\n" +
	"\x10GetMoviesByGenre\x12\x15.scraper.GenreRequest\x1a\x15.scraper.ListResponse\x12=\n" +
	"\fSearchMovies\x12\x16.scraper.SearchRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetMoviesByFeature\x12\x17.scraper.FeatureRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetMoviesByCountry\x12\x17.scraper.CountryRequest\x1a\x15.scraper.ListResponse\x12>\n" +
	"\x0fGetMoviesByYear\x12\x14.scraper.YearRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x0eGetSpecialPage\x12\x1b.scraper.SpecialPageRequest\x1a\x15.scraper.ListResponse\x12K\n" +
	"\x0eGetMovieDetail\x12\x1b.scraper.MovieDetailRequest\x1a\x1c.scraper.MovieDetailResponse\x126\n" +
	"\rGetSeriesHome\x12\x0e.scraper.Empty\x1a\x15.scraper.HomeResponse\x12@\n" +
	"\x10GetSeriesByGenre\x12\x15.scraper.GenreRequest\x1a\x15.scraper.ListResponse\x12=\n" +
	"\fSearchSeries\x12\x16.scraper.SearchRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetSeriesByFeature\x12\x17.scraper.FeatureRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetSeriesByCountry\x12\x17.scraper.CountryRequest\x1a\x15.scraper.ListResponse\x12>\n" +
	"\x0fGetSeriesByYear\x12\x14.scraper.YearRequest\x1a\x15.scraper.ListResponse\x12J\n" +
	"\x14GetSeriesSpecialPage\x12\x1b.scraper.SpecialPageRequest\x1a\x15.scraper.ListResponse\x12M\n" +
	"\x0fGetSeriesDetail\x12\x1b.scraper.MovieDetailRequest\x1a\x1d.scraper.SeriesDetailResponse\x12Q\n" +
	"\x10GetSeriesEpisode\x12\x1d.scraper.SeriesEpisodeRequest\x1a\x1e.scraper.SeriesEpisodeResponse\x12G\n" +
	"\x0eGetAnimeLatest\x12\x19.scraper.AnimePageRequest\x1a\x1a.scraper.AnimeListResponse\x12F\n" +
	"\vSearchAnime\x12\x1b.scraper.AnimeSearchRequest\x1a\x1a.scraper.AnimeListResponse\x12H\n" +
	"\x0fGetAnimeOngoing\x12\x19.scraper.AnimePageRequest\x1a\x1a.scraper.AnimeListResponse\x12>\n" +
	"\x0eGetAnimeGenres\x12\x0e.scraper.Empty\x1a\x1c.scraper.AnimeGenresResponse\x12H\n" +
	"\x0eGetAnimeDetail\x12\x18.scraper.AnimeUrlRequest\x1a\x1c.scraper.AnimeDetailResponse\x12J\n" +
	"\x0fGetAnimeEpisode\x12\x18.scraper.AnimeUrlRequest\x1a\x1d.scraper.AnimeEpisodeResponseB\x19Z\x17tubexxi/video-api/protob\x06proto3"

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData []byte
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)))
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_scraper_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: scraper.Empty
	(*ListRequest)(nil),           // 1: scraper.ListRequest
	(*GenreRequest)(nil),          // 2: scraper.GenreRequest
	(*SearchRequest)(nil),         // 3: scraper.SearchRequest
	(*FeatureRequest)(nil),        // 4: scraper.FeatureRequest
	(*CountryRequest)(nil),        // 5: scraper.CountryRequest
	(*YearRequest)(nil),           // 6: scraper.YearRequest
	(*SpecialPageRequest)(nil),    // 7: scraper.SpecialPageRequest
	(*MovieDetailRequest)(nil),    // 8: scraper.MovieDetailRequest
	(*Movie)(nil),                 // 9: scraper.Movie
	(*HomeSection)(nil),           // 10: scraper.HomeSection
	(*HomeResponse)(nil),          // 11: scraper.HomeResponse
	(*Pagination)(nil),            // 12: scraper.Pagination
	(*ListResponse)(nil),          // 13: scraper.ListResponse
	(*PlayerUrl)(nil),             // 14: scraper.PlayerUrl
	(*MoviePerson)(nil),           // 15: scraper.MoviePerson
	(*CountryMovie)(nil),          // 16: scraper.CountryMovie
	(*Genre)(nil),                 // 17: scraper.Genre
	(*MovieDetail)(nil),           // 18: scraper.MovieDetail
	(*MovieDetailResponse)(nil),   // 19: scraper.MovieDetailResponse
	(*SeriesEpisodeRequest)(nil),  // 20: scraper.SeriesEpisodeRequest
	(*SeriesEpisodeResponse)(nil), // 21: scraper.SeriesEpisodeResponse
	(*EpisodeList)(nil),           // 22: scraper.EpisodeList
	(*SeasonList)(nil),            // 23: scraper.SeasonList
	(*SeriesDetail)(nil),          // 24: scraper.SeriesDetail
	(*SeriesDetailResponse)(nil),  // 25: scraper.SeriesDetailResponse
	(*AnimeGenre)(nil),            // 26: scraper.AnimeGenre
	(*Anime)(nil),                 // 27: scraper.Anime
	(*AnimeEpisode)(nil),          // 28: scraper.AnimeEpisode
	(*AnimeEpisodeItem)(nil),      // 29: scraper.AnimeEpisodeItem
	(*AnimeDownloadLink)(nil),     // 30: scraper.AnimeDownloadLink
	(*PaginationAnime)(nil),       // 31: scraper.PaginationAnime
	(*AnimeListResponse)(nil),     // 32: scraper.AnimeListResponse
	(*AnimeGenresResponse)(nil),   // 33: scraper.AnimeGenresResponse
	(*AnimePageRequest)(nil),      // 34: scraper.AnimePageRequest
	(*AnimeSearchRequest)(nil),    // 35: scraper.AnimeSearchRequest
	(*AnimeUrlRequest)(nil),       // 36: scraper.AnimeUrlRequest
	(*AnimeDetailResponse)(nil),   // 37: scraper.AnimeDetailResponse
	(*AnimeEpisodeResponse)(nil),  // 38: scraper.AnimeEpisodeResponse
}
var file_proto_scraper_proto_depIdxs = []int32{
	9,  // 0: scraper.HomeSection.value:type_name -> scraper.Movie
	10, // 1: scraper.HomeResponse.sections:type_name -> scraper.HomeSection
	9,  // 2: scraper.ListResponse.movies:type_name -> scraper.Movie
	12, // 3: scraper.ListResponse.pagination:type_name -> scraper.Pagination
	9,  // 4: scraper.MovieDetail.movie:type_name -> scraper.Movie
	14, // 5: scraper.MovieDetail.player_urls:type_name -> scraper.PlayerUrl
	15, // 6: scraper.MovieDetail.directors:type_name -> scraper.MoviePerson
	15, // 7: scraper.MovieDetail.movie_stars:type_name -> scraper.MoviePerson
	16, // 8: scraper.MovieDetail.countries:type_name -> scraper.CountryMovie
	17, // 9: scraper.MovieDetail.genres:type_name -> scraper.Genre
	9,  // 10: scraper.MovieDetail.similar_movies:type_name -> scraper.Movie
	18, // 11: scraper.MovieDetailResponse.detail:type_name -> scraper.MovieDetail
	14, // 12: scraper.SeriesEpisodeResponse.player_urls:type_name -> scraper.PlayerUrl
	14, // 13: scraper.EpisodeList.player_urls:type_name -> scraper.PlayerUrl
	22, // 14: scraper.SeasonList.episode_list:type_name -> scraper.EpisodeList
	18, // 15: scraper.SeriesDetail.movie_detail:type_name -> scraper.MovieDetail
	23, // 16: scraper.SeriesDetail.season_list:type_name -> scraper.SeasonList
	24, // 17: scraper.SeriesDetailResponse.detail:type_name -> scraper.SeriesDetail
	26, // 18: scraper.Anime.genre:type_name -> scraper.AnimeGenre
	28, // 19: scraper.Anime.episodes:type_name -> scraper.AnimeEpisode
	29, // 20: scraper.AnimeEpisode.list_episode:type_name -> scraper.AnimeEpisodeItem
	30, // 21: scraper.AnimeEpisode.download_links:type_name -> scraper.AnimeDownloadLink
	27, // 22: scraper.AnimeListResponse.animes:type_name -> scraper.Anime
	31, // 23: scraper.AnimeListResponse.pagination:type_name -> scraper.PaginationAnime
	26, // 24: scraper.AnimeGenresResponse.genres:type_name -> scraper.AnimeGenre
	27, // 25: scraper.AnimeDetailResponse.anime:type_name -> scraper.Anime
	28, // 26: scraper.AnimeEpisodeResponse.episode:type_name -> scraper.AnimeEpisode
	0,  // 27: scraper.ScraperService.ScrapeHome:input_type -> scraper.Empty
	1,  // 28: scraper.ScraperService.ScrapeList:input_type -> scraper.ListRequest
	2,  // 29: scraper.ScraperService.GetMoviesByGenre:input_type -> scraper.GenreRequest
	3,  // 30: scraper.ScraperService.SearchMovies:input_type -> scraper.SearchRequest
	4,  // 31: scraper.ScraperService.GetMoviesByFeature:input_type -> scraper.FeatureRequest
	5,  // 32: scraper.ScraperService.GetMoviesByCountry:input_type -> scraper.CountryRequest
	6,  // 33: scraper.ScraperService.GetMoviesByYear:input_type -> scraper.YearRequest
	7,  // 34: scraper.ScraperService.GetSpecialPage:input_type -> scraper.SpecialPageRequest
	8,  // 35: scraper.ScraperService.GetMovieDetail:input_type -> scraper.MovieDetailRequest
	0,  // 36: scraper.ScraperService.GetSeriesHome:input_type -> scraper.Empty
	2,  // 37: scraper.ScraperService.GetSeriesByGenre:input_type -> scraper.GenreRequest
	3,  // 38: scraper.ScraperService.SearchSeries:input_type -> scraper.SearchRequest
	4,  // 39: scraper.ScraperService.GetSeriesByFeature:input_type -> scraper.FeatureRequest
	5,  // 40: scraper.ScraperService.GetSeriesByCountry:input_type -> scraper.CountryRequest
	6,  // 41: scraper.ScraperService.GetSeriesByYear:input_type -> scraper.YearRequest
	7,  // 42: scraper.ScraperService.GetSeriesSpecialPage:input_type -> scraper.SpecialPageRequest
	8,  // 43: scraper.ScraperService.GetSeriesDetail:input_type -> scraper.MovieDetailRequest
	20, // 44: scraper.ScraperService.GetSeriesEpisode:input_type -> scraper.SeriesEpisodeRequest
	34, // 45: scraper.ScraperService.GetAnimeLatest:input_type -> scraper.AnimePageRequest
	35, // 46: scraper.ScraperService.SearchAnime:input_type -> scraper.AnimeSearchRequest
	34, // 47: scraper.ScraperService.GetAnimeOngoing:input_type -> scraper.AnimePageRequest
	0,  // 48: scraper.ScraperService.GetAnimeGenres:input_type -> scraper.Empty
	36, // 49: scraper.ScraperService.GetAnimeDetail:input_type -> scraper.AnimeUrlRequest
	36, // 50: scraper.ScraperService.GetAnimeEpisode:input_type -> scraper.AnimeUrlRequest
	11, // 51: scraper.ScraperService.ScrapeHome:output_type -> scraper.HomeResponse
	13, // 52: scraper.ScraperService.ScrapeList:output_type -> scraper.ListResponse
	13, // 53: scraper.ScraperService.GetMoviesByGenre:output_type -> scraper.ListResponse
	13, // 54: scraper.ScraperService.SearchMovies:output_type -> scraper.ListResponse
	13, // 55: scraper.ScraperService.GetMoviesByFeature:output_type -> scraper.ListResponse
	13, // 56: scraper.ScraperService.GetMoviesByCountry:output_type -> scraper.ListResponse
	13, // 57: scraper.ScraperService.GetMoviesByYear:output_type -> scraper.ListResponse
	13, // 58: scraper.ScraperService.GetSpecialPage:output_type -> scraper.ListResponse
	19, // 59: scraper.ScraperService.GetMovieDetail:output_type -> scraper.MovieDetailResponse
	11, // 60: scraper.ScraperService.GetSeriesHome:output_type -> scraper.HomeResponse
	13, // 61: scraper.ScraperService.GetSeriesByGenre:output_type -> scraper.ListResponse
	13, // 62: scraper.ScraperService.SearchSeries:output_type -> scraper.ListResponse
	13, // 63: scraper.ScraperService.GetSeriesByFeature:output_type -> scraper.ListResponse
	13, // 64: scraper.ScraperService.GetSeriesByCountry:output_type -> scraper.ListResponse
	13, // 65: scraper.ScraperService.GetSeriesByYear:output_type -> scraper.ListResponse
	13, // 66: scraper.ScraperService.GetSeriesSpecialPage:output_type -> scraper.ListResponse
	25, // 67: scraper.ScraperService.GetSeriesDetail:output_type -> scraper.SeriesDetailResponse
	21, // 68: scraper.ScraperService.GetSeriesEpisode:output_type -> scraper.SeriesEpisodeResponse
	32, // 69: scraper.ScraperService.GetAnimeLatest:output_type -> scraper.AnimeListResponse
	32, // 70: scraper.ScraperService.SearchAnime:output_type -> scraper.AnimeListResponse
	32, // 71: scraper.ScraperService.GetAnimeOngoing:output_type -> scraper.AnimeListResponse
	33, // 72: scraper.ScraperService.GetAnimeGenres:output_type -> scraper.AnimeGenresResponse
	37, // 73: scraper.ScraperService.GetAnimeDetail:output_type -> scraper.AnimeDetailResponse
	38, // 74: scraper.ScraperService.GetAnimeEpisode:output_type -> scraper.AnimeEpisodeResponse
	51, // [51:75] is the sub-list for method output_type
	27, // [27:51] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	file_proto_scraper_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_scraper_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_scraper_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_scraper_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
