// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: scraper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScraperService_ScrapeHome_FullMethodName         = "/scraper.ScraperService/ScrapeHome"
	ScraperService_ScrapeList_FullMethodName         = "/scraper.ScraperService/ScrapeList"
	ScraperService_GetMoviesByGenre_FullMethodName   = "/scraper.ScraperService/GetMoviesByGenre"
	ScraperService_SearchMovies_FullMethodName       = "/scraper.ScraperService/SearchMovies"
	ScraperService_GetMoviesByFeature_FullMethodName = "/scraper.ScraperService/GetMoviesByFeature"
	ScraperService_GetMoviesByCountry_FullMethodName = "/scraper.ScraperService/GetMoviesByCountry"
	ScraperService_GetMoviesByYear_FullMethodName    = "/scraper.ScraperService/GetMoviesByYear"
	ScraperService_GetSpecialPage_FullMethodName     = "/scraper.ScraperService/GetSpecialPage"
)

// ScraperServiceClient is the client API for ScraperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScraperServiceClient interface {
	ScrapeHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HomeResponse, error)
	ScrapeList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// New RPCs
	GetMoviesByGenre(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*ListResponse, error)
	SearchMovies(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetMoviesByFeature(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetMoviesByCountry(ctx context.Context, in *CountryRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetMoviesByYear(ctx context.Context, in *YearRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetSpecialPage(ctx context.Context, in *SpecialPageRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type scraperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperServiceClient(cc grpc.ClientConnInterface) ScraperServiceClient {
	return &scraperServiceClient{cc}
}

func (c *scraperServiceClient) ScrapeHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, ScraperService_ScrapeHome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) ScrapeList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_ScrapeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) GetMoviesByGenre(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_GetMoviesByGenre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) SearchMovies(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_SearchMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) GetMoviesByFeature(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_GetMoviesByFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) GetMoviesByCountry(ctx context.Context, in *CountryRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_GetMoviesByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) GetMoviesByYear(ctx context.Context, in *YearRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_GetMoviesByYear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) GetSpecialPage(ctx context.Context, in *SpecialPageRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ScraperService_GetSpecialPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperServiceServer is the server API for ScraperService service.
// All implementations must embed UnimplementedScraperServiceServer
// for forward compatibility.
type ScraperServiceServer interface {
	ScrapeHome(context.Context, *Empty) (*HomeResponse, error)
	ScrapeList(context.Context, *ListRequest) (*ListResponse, error)
	// New RPCs
	GetMoviesByGenre(context.Context, *GenreRequest) (*ListResponse, error)
	SearchMovies(context.Context, *SearchRequest) (*ListResponse, error)
	GetMoviesByFeature(context.Context, *FeatureRequest) (*ListResponse, error)
	GetMoviesByCountry(context.Context, *CountryRequest) (*ListResponse, error)
	GetMoviesByYear(context.Context, *YearRequest) (*ListResponse, error)
	GetSpecialPage(context.Context, *SpecialPageRequest) (*ListResponse, error)
	mustEmbedUnimplementedScraperServiceServer()
}

// UnimplementedScraperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScraperServiceServer struct{}

func (UnimplementedScraperServiceServer) ScrapeHome(context.Context, *Empty) (*HomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrapeHome not implemented")
}
func (UnimplementedScraperServiceServer) ScrapeList(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrapeList not implemented")
}
func (UnimplementedScraperServiceServer) GetMoviesByGenre(context.Context, *GenreRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoviesByGenre not implemented")
}
func (UnimplementedScraperServiceServer) SearchMovies(context.Context, *SearchRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMovies not implemented")
}
func (UnimplementedScraperServiceServer) GetMoviesByFeature(context.Context, *FeatureRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoviesByFeature not implemented")
}
func (UnimplementedScraperServiceServer) GetMoviesByCountry(context.Context, *CountryRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoviesByCountry not implemented")
}
func (UnimplementedScraperServiceServer) GetMoviesByYear(context.Context, *YearRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoviesByYear not implemented")
}
func (UnimplementedScraperServiceServer) GetSpecialPage(context.Context, *SpecialPageRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpecialPage not implemented")
}
func (UnimplementedScraperServiceServer) mustEmbedUnimplementedScraperServiceServer() {}
func (UnimplementedScraperServiceServer) testEmbeddedByValue()                        {}

// UnsafeScraperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperServiceServer will
// result in compilation errors.
type UnsafeScraperServiceServer interface {
	mustEmbedUnimplementedScraperServiceServer()
}

func RegisterScraperServiceServer(s grpc.ServiceRegistrar, srv ScraperServiceServer) {
	// If the following call panics, it indicates UnimplementedScraperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScraperService_ServiceDesc, srv)
}

func _ScraperService_ScrapeHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).ScrapeHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_ScrapeHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).ScrapeHome(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_ScrapeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).ScrapeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_ScrapeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).ScrapeList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_GetMoviesByGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).GetMoviesByGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_GetMoviesByGenre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).GetMoviesByGenre(ctx, req.(*GenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_SearchMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).SearchMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_SearchMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).SearchMovies(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_GetMoviesByFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).GetMoviesByFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_GetMoviesByFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).GetMoviesByFeature(ctx, req.(*FeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_GetMoviesByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).GetMoviesByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_GetMoviesByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).GetMoviesByCountry(ctx, req.(*CountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_GetMoviesByYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).GetMoviesByYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_GetMoviesByYear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).GetMoviesByYear(ctx, req.(*YearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_GetSpecialPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpecialPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).GetSpecialPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_GetSpecialPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).GetSpecialPage(ctx, req.(*SpecialPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScraperService_ServiceDesc is the grpc.ServiceDesc for ScraperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScraperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.ScraperService",
	HandlerType: (*ScraperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScrapeHome",
			Handler:    _ScraperService_ScrapeHome_Handler,
		},
		{
			MethodName: "ScrapeList",
			Handler:    _ScraperService_ScrapeList_Handler,
		},
		{
			MethodName: "GetMoviesByGenre",
			Handler:    _ScraperService_GetMoviesByGenre_Handler,
		},
		{
			MethodName: "SearchMovies",
			Handler:    _ScraperService_SearchMovies_Handler,
		},
		{
			MethodName: "GetMoviesByFeature",
			Handler:    _ScraperService_GetMoviesByFeature_Handler,
		},
		{
			MethodName: "GetMoviesByCountry",
			Handler:    _ScraperService_GetMoviesByCountry_Handler,
		},
		{
			MethodName: "GetMoviesByYear",
			Handler:    _ScraperService_GetMoviesByYear_Handler,
		},
		{
			MethodName: "GetSpecialPage",
			Handler:    _ScraperService_GetSpecialPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}
