// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenreRequest) Reset() {
	*x = GenreRequest{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreRequest) ProtoMessage() {}

func (x *GenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreRequest.ProtoReflect.Descriptor instead.
func (*GenreRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GenreRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GenreRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// populer, most-commented, rating, release, latest
	FeatureType   string `protobuf:"bytes,1,opt,name=feature_type,json=featureType,proto3" json:"feature_type,omitempty"`
	Page          int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureRequest) Reset() {
	*x = FeatureRequest{}
	mi := &file_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRequest) ProtoMessage() {}

func (x *FeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRequest.ProtoReflect.Descriptor instead.
func (*FeatureRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureRequest) GetFeatureType() string {
	if x != nil {
		return x.FeatureType
	}
	return ""
}

func (x *FeatureRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type CountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountrySlug   string                 `protobuf:"bytes,1,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryRequest) Reset() {
	*x = CountryRequest{}
	mi := &file_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryRequest) ProtoMessage() {}

func (x *CountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryRequest.ProtoReflect.Descriptor instead.
func (*CountryRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *CountryRequest) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

func (x *CountryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type YearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearRequest) Reset() {
	*x = YearRequest{}
	mi := &file_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearRequest) ProtoMessage() {}

func (x *YearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearRequest.ProtoReflect.Descriptor instead.
func (*YearRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *YearRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SpecialPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageName      string                 `protobuf:"bytes,1,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialPageRequest) Reset() {
	*x = SpecialPageRequest{}
	mi := &file_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialPageRequest) ProtoMessage() {}

func (x *SpecialPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialPageRequest.ProtoReflect.Descriptor instead.
func (*SpecialPageRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *SpecialPageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *SpecialPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Movie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle   *string                `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3,oneof" json:"original_title,omitempty"`
	Thumbnail       *string                `protobuf:"bytes,4,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	Synopsis        *string                `protobuf:"bytes,5,opt,name=synopsis,proto3,oneof" json:"synopsis,omitempty"`
	Rating          *float32               `protobuf:"fixed32,6,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Duration        *int64                 `protobuf:"varint,7,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Year            *int32                 `protobuf:"varint,8,opt,name=year,proto3,oneof" json:"year,omitempty"`
	DatePublished   *string                `protobuf:"bytes,9,opt,name=date_published,json=datePublished,proto3,oneof" json:"date_published,omitempty"`
	LabelQuality    *string                `protobuf:"bytes,10,opt,name=label_quality,json=labelQuality,proto3,oneof" json:"label_quality,omitempty"`
	Genre           *string                `protobuf:"bytes,11,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	OriginalPageUrl *string                `protobuf:"bytes,12,opt,name=original_page_url,json=originalPageUrl,proto3,oneof" json:"original_page_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetOriginalTitle() string {
	if x != nil && x.OriginalTitle != nil {
		return *x.OriginalTitle
	}
	return ""
}

func (x *Movie) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *Movie) GetSynopsis() string {
	if x != nil && x.Synopsis != nil {
		return *x.Synopsis
	}
	return ""
}

func (x *Movie) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Movie) GetDuration() int64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Movie) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Movie) GetDatePublished() string {
	if x != nil && x.DatePublished != nil {
		return *x.DatePublished
	}
	return ""
}

func (x *Movie) GetLabelQuality() string {
	if x != nil && x.LabelQuality != nil {
		return *x.LabelQuality
	}
	return ""
}

func (x *Movie) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *Movie) GetOriginalPageUrl() string {
	if x != nil && x.OriginalPageUrl != nil {
		return *x.OriginalPageUrl
	}
	return ""
}

type HomeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []*Movie               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	ViewAllUrl    *string                `protobuf:"bytes,3,opt,name=view_all_url,json=viewAllUrl,proto3,oneof" json:"view_all_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeSection) Reset() {
	*x = HomeSection{}
	mi := &file_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeSection) ProtoMessage() {}

func (x *HomeSection) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeSection.ProtoReflect.Descriptor instead.
func (*HomeSection) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *HomeSection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HomeSection) GetValue() []*Movie {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HomeSection) GetViewAllUrl() string {
	if x != nil && x.ViewAllUrl != nil {
		return *x.ViewAllUrl
	}
	return ""
}

type HomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*HomeSection         `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeResponse) Reset() {
	*x = HomeResponse{}
	mi := &file_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeResponse) ProtoMessage() {}

func (x *HomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeResponse.ProtoReflect.Descriptor instead.
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *HomeResponse) GetSections() []*HomeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPage     int32                  `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,4,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	NextPageUrl   *string                `protobuf:"bytes,5,opt,name=next_page_url,json=nextPageUrl,proto3,oneof" json:"next_page_url,omitempty"`
	PrevPageUrl   *string                `protobuf:"bytes,6,opt,name=prev_page_url,json=prevPageUrl,proto3,oneof" json:"prev_page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pagination) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

func (x *Pagination) GetNextPageUrl() string {
	if x != nil && x.NextPageUrl != nil {
		return *x.NextPageUrl
	}
	return ""
}

func (x *Pagination) GetPrevPageUrl() string {
	if x != nil && x.PrevPageUrl != nil {
		return *x.PrevPageUrl
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *ListResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\ascraper\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\vListRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"6\n" +
	"\fGenreRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"9\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"G\n" +
	"\x0eFeatureRequest\x12!\n" +
	"\ffeature_type\x18\x01 \x01(\tR\vfeatureType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"G\n" +
	"\x0eCountryRequest\x12!\n" +
	"\fcountry_slug\x18\x01 \x01(\tR\vcountrySlug\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"5\n" +
	"\vYearRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"E\n" +
	"\x12SpecialPageRequest\x12\x1b\n" +
	"\tpage_name\x18\x01 \x01(\tR\bpageName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"\xaa\x04\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tH\x00R\roriginalTitle\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\x04 \x01(\tH\x01R\tthumbnail\x88\x01\x01\x12\x1f\n" +
	"\bsynopsis\x18\x05 \x01(\tH\x02R\bsynopsis\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x06 \x01(\x02H\x03R\x06rating\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\a \x01(\x03H\x04R\bduration\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\b \x01(\x05H\x05R\x04year\x88\x01\x01\x12*\n" +
	"\x0edate_published\x18\t \x01(\tH\x06R\rdatePublished\x88\x01\x01\x12(\n" +
	"\rlabel_quality\x18\n" +
	" \x01(\tH\aR\flabelQuality\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\v \x01(\tH\bR\x05genre\x88\x01\x01\x12/\n" +
	"\x11original_page_url\x18\f \x01(\tH\tR\x0foriginalPageUrl\x88\x01\x01B\x11\n" +
	"\x0f_original_titleB\f\n" +
	"\n" +
	"_thumbnailB\v\n" +
	"\t_synopsisB\t\n" +
	"\a_ratingB\v\n" +
	"\t_durationB\a\n" +
	"\x05_yearB\x11\n" +
	"\x0f_date_publishedB\x10\n" +
	"\x0e_label_qualityB\b\n" +
	"\x06_genreB\x14\n" +
	"\x12_original_page_url\"}\n" +
	"\vHomeSection\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x03(\v2\x0e.scraper.MovieR\x05value\x12%\n" +
	"\fview_all_url\x18\x03 \x01(\tH\x00R\n" +
	"viewAllUrl\x88\x01\x01B\x0f\n" +
	"\r_view_all_url\"@\n" +
	"\fHomeResponse\x120\n" +
	"\bsections\x18\x01 \x03(\v2\x14.scraper.HomeSectionR\bsections\"\xfa\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1d\n" +
	"\n" +
	"total_page\x18\x02 \x01(\x05R\ttotalPage\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x04 \x01(\bR\ahasPrev\x12'\n" +
	"\rnext_page_url\x18\x05 \x01(\tH\x00R\vnextPageUrl\x88\x01\x01\x12'\n" +
	"\rprev_page_url\x18\x06 \x01(\tH\x01R\vprevPageUrl\x88\x01\x01B\x10\n" +
	"\x0e_next_page_urlB\x10\n" +
	"\x0e_prev_page_url\"k\n" +
	"\fListResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.scraper.MovieR\x06movies\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.scraper.PaginationR\n" +
	"pagination2\x93\x04\n" +
	"\x0eScraperService\x123\n" +
	"\n" +
	"ScrapeHome\x12\x0e.scraper.Empty\x1a\x15.scraper.HomeResponse\x129\n" +
	"\n" +
	"ScrapeList\x12\x14.scraper.ListRequest\x1a\x15.scraper.ListResponse\x12@\n" +
	"\x10GetMoviesByGenre\x12\x15.scraper.GenreRequest\x1a\x15.scraper.ListResponse\x12=\n" +
	"\fSearchMovies\x12\x16.scraper.SearchRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetMoviesByFeature\x12\x17.scraper.FeatureRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x12GetMoviesByCountry\x12\x17.scraper.CountryRequest\x1a\x15.scraper.ListResponse\x12>\n" +
	"\x0fGetMoviesByYear\x12\x14.scraper.YearRequest\x1a\x15.scraper.ListResponse\x12D\n" +
	"\x0eGetSpecialPage\x12\x1b.scraper.SpecialPageRequest\x1a\x15.scraper.ListResponseB\x19Z\x17tubexxi/video-api/protob\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_scraper_proto_goTypes = []any{
	(*Empty)(nil),              // 0: scraper.Empty
	(*ListRequest)(nil),        // 1: scraper.ListRequest
	(*GenreRequest)(nil),       // 2: scraper.GenreRequest
	(*SearchRequest)(nil),      // 3: scraper.SearchRequest
	(*FeatureRequest)(nil),     // 4: scraper.FeatureRequest
	(*CountryRequest)(nil),     // 5: scraper.CountryRequest
	(*YearRequest)(nil),        // 6: scraper.YearRequest
	(*SpecialPageRequest)(nil), // 7: scraper.SpecialPageRequest
	(*Movie)(nil),              // 8: scraper.Movie
	(*HomeSection)(nil),        // 9: scraper.HomeSection
	(*HomeResponse)(nil),       // 10: scraper.HomeResponse
	(*Pagination)(nil),         // 11: scraper.Pagination
	(*ListResponse)(nil),       // 12: scraper.ListResponse
}
var file_scraper_proto_depIdxs = []int32{
	8,  // 0: scraper.HomeSection.value:type_name -> scraper.Movie
	9,  // 1: scraper.HomeResponse.sections:type_name -> scraper.HomeSection
	8,  // 2: scraper.ListResponse.movies:type_name -> scraper.Movie
	11, // 3: scraper.ListResponse.pagination:type_name -> scraper.Pagination
	0,  // 4: scraper.ScraperService.ScrapeHome:input_type -> scraper.Empty
	1,  // 5: scraper.ScraperService.ScrapeList:input_type -> scraper.ListRequest
	2,  // 6: scraper.ScraperService.GetMoviesByGenre:input_type -> scraper.GenreRequest
	3,  // 7: scraper.ScraperService.SearchMovies:input_type -> scraper.SearchRequest
	4,  // 8: scraper.ScraperService.GetMoviesByFeature:input_type -> scraper.FeatureRequest
	5,  // 9: scraper.ScraperService.GetMoviesByCountry:input_type -> scraper.CountryRequest
	6,  // 10: scraper.ScraperService.GetMoviesByYear:input_type -> scraper.YearRequest
	7,  // 11: scraper.ScraperService.GetSpecialPage:input_type -> scraper.SpecialPageRequest
	10, // 12: scraper.ScraperService.ScrapeHome:output_type -> scraper.HomeResponse
	12, // 13: scraper.ScraperService.ScrapeList:output_type -> scraper.ListResponse
	12, // 14: scraper.ScraperService.GetMoviesByGenre:output_type -> scraper.ListResponse
	12, // 15: scraper.ScraperService.SearchMovies:output_type -> scraper.ListResponse
	12, // 16: scraper.ScraperService.GetMoviesByFeature:output_type -> scraper.ListResponse
	12, // 17: scraper.ScraperService.GetMoviesByCountry:output_type -> scraper.ListResponse
	12, // 18: scraper.ScraperService.GetMoviesByYear:output_type -> scraper.ListResponse
	12, // 19: scraper.ScraperService.GetSpecialPage:output_type -> scraper.ListResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	file_scraper_proto_msgTypes[8].OneofWrappers = []any{}
	file_scraper_proto_msgTypes[9].OneofWrappers = []any{}
	file_scraper_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
